export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCE = 'ADD_PRODUCT_SUCCE';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_DOWNLOAD_PRODUCTS = 'START_DOWNLOAD_PRODUCTS';
export const DOWNLOAD_PRODUCTS_SUCCE = 'DOWNLOAD_PRODUCTS_SUCCE';
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR';

export const GET_REMOVE_PRODUCT = 'GET_REMOVE_PRODUCT';
export const REMOVE_PRODUCT_SUCCE = 'REMOVE_PRODUCT_SUCCE';
export const REMOVE_PRODUCT_ERROR = 'REMOVE_PRODUCT_ERROR';

export const GET_PRODUCT_EDIT = 'GET_PRODUCT_EDIT';
export const START_EDITING_PRODUCT = 'START_EDITING_PRODUCT';
export const EDIT_PRODUCT_SUCCE = 'EDIT_PRODUCT_SUCCE';
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR';