export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCE = 'ADD_PRODUCT_SUCCE';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_DOWNLOAD_PRODUCTS = 'START_DOWNLOAD_PRODUCTS';
export const DOWNLOAD_PRODUCTS_SUCCE = 'DOWNLOAD_PRODUCTS_SUCCE';
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR';

export const GET_REMOVE_PRODUCT = 'GET_REMOVE_PRODUCT';
export const REMOVE_PRODUCT_SUCCE = 'REMOVE_PRODUCT_SUCCE';
export const REMOVE_PRODUCT_ERROR = 'REMOVE_PRODUCT_ERROR';