export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCE = 'ADD_PRODUCT_SUCCE';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_DOWNLOAD_PRODUCTS = 'START_DOWNLOAD_PRODUCTS';
export const START_DOWNLOAD_PRODUCTS_SUCCE = 'DOWNLOAD_PRODUCTS_SUCCE';
export const START_DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR';